"use client";

import { useMemo, useState } from "react";
import { Heart, MessageCircle, Share2, Repeat, Wand2, Sparkles } from "lucide-react";
import { AI_PROVIDERS } from "@/app/lib/ai/providers";
import { MOCK_FEED, type FeedPost } from "@/app/lib/mockData";
import { formatNumber } from "@/app/lib/utils";

const defaultModel = AI_PROVIDERS[0]?.models[0]?.id || "gpt-4-turbo-preview";

export default function FeedPage() {
  const [posts, setPosts] = useState<FeedPost[]>(MOCK_FEED);
  const [draft, setDraft] = useState({ prompt: "", model: defaultModel });

  const modelOptions = useMemo(
    () =>
      AI_PROVIDERS.flatMap((p) => p.models.map((m) => ({ id: m.id, name: m.name, provider: p.name }))),
    []
  );

  const publish = () => {
    if (!draft.prompt.trim()) return;
    const model = modelOptions.find((m) => m.id === draft.model);
    const newPost: FeedPost = {
      id: `local-${Date.now()}`,
      author: {
        name: "You",
        handle: "@you",
        avatar: "https://avatars.githubusercontent.com/u/4?v=4",
        reputation: 80,
      },
      model: draft.model,
      prompt: draft.prompt,
      output: `Draft output generated by ${model?.name || "model"}.`,
      tags: ["remix-ready", model?.provider || "custom"],
      likes: 0,
      comments: 0,
      remixes: 0,
      timestamp: "just now",
    };
    setPosts((prev) => [newPost, ...prev]);
    setDraft({ prompt: "", model: draft.model });
  };

  const toggleLike = (id: string) => {
    setPosts((prev) =>
      prev.map((p) => (p.id === id ? { ...p, likes: p.likes + 1 } : p))
    );
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-[#0b0a13] via-[#0f0c1c] to-[#05030d] text-white">
      <div className="mx-auto max-w-5xl px-4 py-10 space-y-8">
        <header className="flex items-center justify-between">
          <div>
            <p className="text-sm text-white/60">AI-first social feed</p>
            <h1 className="text-2xl font-semibold">PRIMEX Social</h1>
          </div>
          <div className="flex items-center gap-2 rounded-full border border-purple-500/40 bg-purple-500/10 px-3 py-1 text-sm">
            <Sparkles className="h-4 w-4 text-purple-300" />
            Everything here is AI-generated or AI-assisted.
          </div>
        </header>

        <section className="rounded-2xl border border-white/10 bg-white/5 p-5 shadow-2xl shadow-purple-500/10 backdrop-blur">
          <div className="flex items-start gap-4">
            <div className="h-10 w-10 rounded-full bg-gradient-to-br from-purple-500 to-pink-500" />
            <div className="flex-1 space-y-3">
              <textarea
                value={draft.prompt}
                onChange={(e) => setDraft((d) => ({ ...d, prompt: e.target.value }))}
                placeholder="Describe what you want your AI post to say or show..."
                className="w-full rounded-xl border border-white/10 bg-black/40 px-3 py-2 text-sm outline-none focus:border-purple-500"
              />
              <div className="flex flex-wrap items-center gap-3">
                <select
                  value={draft.model}
                  onChange={(e) => setDraft((d) => ({ ...d, model: e.target.value }))}
                  className="rounded-lg border border-white/10 bg-black/50 px-3 py-2 text-sm outline-none focus:border-purple-500"
                >
                  {modelOptions.map((m) => (
                    <option key={m.id} value={m.id}>{`${m.name} · ${m.provider}`}</option>
                  ))}
                </select>
                <button
                  onClick={publish}
                  className="inline-flex items-center gap-2 rounded-lg bg-purple-600 px-4 py-2 text-sm font-semibold hover:bg-purple-700 transition-colors"
                >
                  <Wand2 className="h-4 w-4" />
                  Generate & post
                </button>
              </div>
            </div>
          </div>
        </section>

        <div className="space-y-4">
          {posts.map((post) => (
            <article
              key={post.id}
              className="rounded-2xl border border-white/10 bg-white/5 p-5 shadow-lg shadow-purple-500/5 backdrop-blur"
            >
              <div className="flex items-start justify-between gap-3">
                <div className="flex items-start gap-3">
                  <div className="h-10 w-10 rounded-full bg-white/10" />
                  <div>
                    <div className="flex items-center gap-2 text-sm">
                      <span className="font-semibold">{post.author.name}</span>
                      <span className="text-white/60">{post.author.handle}</span>
                      <span className="text-xs text-emerald-300">{post.author.reputation} rep</span>
                    </div>
                    <div className="text-xs text-white/50">{post.timestamp}</div>
                  </div>
                </div>
                <span className="rounded-full bg-purple-500/15 px-3 py-1 text-xs text-purple-200">{post.model}</span>
              </div>

              <div className="mt-3 text-sm text-white/90">
                <p className="text-white/60 text-xs mb-1">Prompt</p>
                <p className="font-medium">{post.prompt}</p>
              </div>

              <div className="mt-3 rounded-xl border border-white/5 bg-black/40 p-4 text-sm leading-relaxed text-white/90">
                {post.output}
              </div>

              <div className="mt-3 flex flex-wrap gap-2">
                {post.tags.map((tag) => (
                  <span key={tag} className="rounded-full border border-white/10 px-3 py-1 text-xs text-white/70">
                    #{tag}
                  </span>
                ))}
              </div>

              <div className="mt-4 flex items-center gap-4 text-sm text-white/70">
                <button
                  onClick={() => toggleLike(post.id)}
                  className="flex items-center gap-1 rounded-full bg-white/5 px-3 py-1 hover:bg-white/10"
                >
                  <Heart className="h-4 w-4" />
                  {formatNumber(post.likes)}
                </button>
                <div className="flex items-center gap-1 rounded-full bg-white/5 px-3 py-1">
                  <MessageCircle className="h-4 w-4" />
                  {formatNumber(post.comments)}
                </div>
                <div className="flex items-center gap-1 rounded-full bg-white/5 px-3 py-1">
                  <Repeat className="h-4 w-4" />
                  {formatNumber(post.remixes)}
                </div>
                <div className="flex items-center gap-1 rounded-full bg-white/5 px-3 py-1">
                  <Share2 className="h-4 w-4" />
                  Share
                </div>
              </div>
            </article>
          ))}
        </div>
      </div>
    </div>
  );
}
